package com.revature.models;

import java.util.ArrayList;
import java.util.Random;

public class Main {
    public static void main(String[] args) {

        // Calls the Random utility from the Java library
        Random random = new Random();
        // Creates an empty array list to store generated Rectangles for comparison
        ArrayList<Rectangle> rectangles = new ArrayList<>();

        // Calls the area and perimeter comparisons
        AreaCompare ac = new AreaCompare();
        PerimeterCompare pc = new PerimeterCompare();

        // Defines two Rectangles that will represent the largest Rectangle generated by area and perimeter
        Rectangle maxArea = new Rectangle();
        Rectangle maxPerim = new Rectangle();

        // Generates a list of 10 Rectangles, assigns the name, height, and width attributes, and then adds them to the "rectangles" list
        for (int i = 0; i < 10; i++) {
            Rectangle r = new Rectangle();
            r.setName("Rectangle " + (i+1));
            r.setHeight(random.nextInt(20)+1);
            r.setWidth(random.nextInt(20)+1);
            rectangles.add(r);
        }

        // Prints out the list of Rectangles, including their areas and perimeters
        for (Rectangle rectangle : rectangles) {
            System.out.println(rectangle + " Area: " + rectangle.getArea() + " Perimeter: " + rectangle.getPerimeter());
        }

        System.out.println("\n------------------------------------------------------------------------------- \n");

        // Iterates through the "rectangles" list and compares the areas of each Rectangle against the rectangle at the index before it
        // as well as against the current largest Rectangle (maxArea)
        for (int i = 1; i < rectangles.size(); i++) {
            if ((ac.isLessThan(rectangles.get(i-1),rectangles.get(i))) && (ac.isLessThan(maxArea,rectangles.get(i)))) {
                maxArea = rectangles.get(i);
            }
        }

        // Iterates through the "rectangles" list and compares the perimeters of each Rectangle against the rectangle at the index before it
        // as well as against the current largest Rectangle (maxPerim)
        for (int i = 1; i < rectangles.size(); i++) {
            if ((pc.isLessThan(rectangles.get(i-1),rectangles.get(i))) && (pc.isLessThan(maxPerim,rectangles.get(i)))) {
                maxPerim = rectangles.get(i);
            }
        }

        // Declares the largest rectangles by area and by perimeter
        System.out.println(maxArea.name + " has the largest area with an area of " + maxArea.getArea());
        System.out.println("\n" + maxPerim.name + " has the largest perimeter with a perimeter of " + maxPerim.getPerimeter());
    }
}
